/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_chibpi_markerbasedar_MarkerDetector */

#ifndef _Included_org_chibpi_markerbasedar_MarkerDetector
#define _Included_org_chibpi_markerbasedar_MarkerDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_chibpi_markerbasedar_MarkerDetector
 * Method:    nativeCreateObject
 * Signature: (FFFF[F)J
 */
JNIEXPORT jlong JNICALL Java_org_chibpi_markerbasedar_MarkerDetector_nativeCreateObject
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloatArray);

/*
 * Class:     org_chibpi_markerbasedar_MarkerDetector
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_chibpi_markerbasedar_MarkerDetector_nativeDestroyObject
  (JNIEnv *, jclass, jlong);


/*
 * Class:     org_chibpi_markerbasedar_MarkerDetector
 * Method:    nativeProcess
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_chibpi_markerbasedar_MarkerDetector_nativeProcess
  (JNIEnv *, jclass, jlong, jlong);


/*
 * Class:     org_chibpi_markerbasedar_MarkerDetector
 * Method:    nativeGetTransformations
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_chibpi_markerbasedar_MarkerDetector_nativeGetTransformations
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
